dist: bionic
sudo: false
language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic-8
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-7
      - lcov
      - clang-format-8

before_install:
  - pip install --user cpp-coveralls

script:
  - ./run-clang-format.py -r tests/ stdin_stdout/ src/ -e tests/gtest --clang-format-executable clang-format-8
  - export CC=gcc-7
  - export CXX=g++-7
  - cd tests
  - mkdir cmake
  - cd cmake/
  - cmake --version
  - cmake ../
  - make
  - ctest --verbose



