dist: bionic
sudo: false
language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test'
    packages:
      - g++-7
      - lcov
      - clang-format-8

before_install:
  - pip install --user cpp-coveralls

script:
  - ./run-clang-format.py -r tests/ stdin_stdout/ src/ -e tests/gtest --clang-format-executable clang-format-8
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake .
  - make
  - cd tests
  - ctest --verbose

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*" -E "usr/.*"





